### PR TITLE
The estimated number of days until the next purchase date is calculated 

### LINKED ISSUE #10: 10. As an item, I want my estimated next purchase date to be computed at the time my purchase is recorded in the database so the app can learn how often I buy different items.
AC:

* When a purchase is recorded, the estimated number of days until the next purchase date should be calculated and recorded in the database

The script `calculateEstimate` from `@the-collab-lab/shopping-list-utils` should be used to calculate the next estimated purchase interval. This should already be installed in your project from [issue 3](https://github.com/the-collab-lab/tcl-33-smart-shopping-list/issues/3)

Notes:

* Think through the data that is needed as inputs to the function in `estimates.js` and how to use the output.
* It is likely at this point you'll need to adjust the schema for an item to accommodate the data points required.

### PR DESCRIPTION
**Pull request by ikramsalim**
## Description
When a purchase is recorded, this code estimates the number of days until the next purchase date, calculates it and records it in the database.
The script calculateEstimate from @the-collab-lab/shopping-list-utils is used to calculate the next estimated purchase interval. 

It adds three inputs which are timesPurchased, lastPurchased and nextDateOfPurchase in the firebase and updates them for each grocery item that is checked. If it is an existing grocery item in the database, all **_**three data inputs**_** change. 
If it's a new grocery item, only **_two data inputs_** are changed in the firebase: timesPurchased equals 1 and lastPurchased is set to new Date(). 

Even though we had the code that was updating firebase in App.js, I moved it to estimate.js file since it made more sense and makes it legible.

- I learnt that calculateEstimate only takes three parameters and for daysSinceLastTransaction, it shouldn't be _this.sinceLastDaysTransaction_ nor _data.sinceLastDaysTransaction_ and you should just use it as it is when calling calculateEstimate.
- I also learnt that I had to convert the variable _lastPurchase_  to millisecond(toMillis) which is a method of TimeUnit Class that is used to get the time represented by the TimeUnit object, as the number of Seconds, since midnight UTC on the **1st January 1970.**

## Related Issue
Closes #10 

## Acceptance Criteria

When a user checks a grocery item: 
> - the estimated number of days until the next purchase date is calculated & recorded in the database
> - The number of times a grocery item is purchased is also recorded in the database
> - The last purchase date of the grocery item is recorded in the database

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

ezgif com-gif-maker (1)

### After

ezgif com-gif-maker (2)

## Testing Steps / QA Criteria

- Be on the main branch of tcl-33-smart-shopping-list
- Git checkout af-is-calculate-estimate to switch to the specific branch
- **npm start** to start the application which will open in your browser
- if you have a token, enter and click View List, check few grocery items and you will see the timesPurchased incrementing by 1
- if you don't have a token, create your own shipping list, add some items then click the ViewList button and check the box which will make the item increment by 1
- To get access to **last purchase date** and **next purchase date** of grocery items, log into the firebase console and you will automatically see those data inputs changing anytime you purchase/check a grocery item.

### CODE REVIEW

**Comment by JenniferToops** [comment]
```import React, { useState } from 'react';
import { useCollection } from 'react-firebase-hooks/firestore';
import { db } from '../lib/firebase';
import ErrorMessage from '../components/ErrorMessage';
import estimatedTime from '../lib/estimate';```

It looks like we aren't using "estimatedTime"--can this be removed?
```import estimatedTime from '../lib/estimate';```

**Comment by JenniferToops** [comment]
```const validateNewListItem = (listItem, list) => {
  const punctuation = /[!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]/g;

  const duplicateItem = list.docs.find((duplicate) => {
    const existingItem = duplicate
      .data()
      .item.toLowerCase()
      .replace(punctuation, '');

    const newItem = listItem.toLowerCase().replace(punctuation, '');
    console.log(newItem);

    return existingItem === newItem;
  });
 ```

I know this isn't your code, but mentors have told us we should remove console.logs... maybe remove?

**Comment by JenniferToops** [comment]
Mentors have mentioned that we should remove console logs after we're done building.... maybe remove console.logs on lines:
20
22
commented console.log on line 33

**Comment by JenniferToops** [comment]
I really, really like how succinct your code is. I haven't worked with dates very much at all and this is really helpful for me.

**Comment by aprilleone** [comment]
@ikramsalim @arvinf07 you have a couple of conflicts that need to be resolved. the easiest way to resolve the conflicts is to pull main in and then return 'npm install' to get a fresh package-lock.json.

Please reach out if you need help on resolving the conflicts on viewlist.

**Review by aprilleone — APPROVED** [review]
@ikramsalim Good work on this. It was a great call moving the functions over to estimate.js.

**Pull request merged**
